### ISSUE TITLE
[S-02-2] UOF + DDPG Implementation

### ISSUE THREAD

**Issue by CUN-bjy** [ropiens/project-sandwich-man#11]
### to-do-list
- [x] Implementation of DDPG + HER only. https://github.com/ropiens/universal-option-framwork-pytorch/pull/3
- [x] Implementation of high-level policy and DIOL. https://github.com/ropiens/universal-option-framwork-pytorch/pull/4
- [x] add AAES https://github.com/ropiens/universal-option-framwork-pytorch/pull/5
- [ ] add Abstract Demonstration.

### Results
- [ropiens/universal-option-framwork-pytorch](https://github.com/ropiens/universal-option-framwork-pytorch)

**Comment by CUN-bjy** [comment]
## Discussion
1. `MountainCarContinuous` has some dependencies between time-series actions.
  - using HAC(Hierarchical Actor Critic), this gap can be handled because all states(position and velocity) could be subgoals.
  - on the other hand, using UOF, the gap couldn't be handled because we cannot choose the optimal subgoals(we don't know exactly about the domain information of environments) 
2. `MountainCarContinuous` has just one final goal and a small range of start position.
  - it makes UOF harder to converge. Since UOF just uses some subgoal(even we don't know exactly this goal is good or not), we cannot get various states and achieved goals for hindsight framework.
